name: Codespell
on:
  pull_request:

jobs:
  codespell:
    name: Run codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: codespell --toml ./tools/pyproject.toml
